### PR TITLE
Fix failed Dispatch Packet on server disconnect

### LINKED ISSUE #26: Failed Dispatch Packet on server disconnect
I'm still debugging, but I'm trying to determine the cause of this error when a player disconnects from it. It logs, depending on the scenario, 2-10 of the same error message that I posted below.

Environment: `itzg/docker-bungeecord`
Velocity: `Velocity 3.2.0-SNAPSHOT (git-36cc2bde-b245)`
Minecraft: `1.19.4`
Plugins:
- `luckperms 5.4.67 by Luck`
- `protocolize v2 by Exceptionflug`
- `velocitab 1.2.3 by William278`
- `venturechat 3.5.0 by Aust1n46`

<details>
<summary>Error Snippet</summary>

```
traxmc-prison-1    | [03:04:20 INFO]: AMTraxTGE joined the game
traxmc-prison-1    | [03:04:20 INFO]: AMTraxTGE[/1xx.xxx.xxx.xxx:xxxxx] logged in with entity id 39 at ([world]0.5, 65.0, 0.5)
traxmc-lobby-1     | [03:04:20 INFO]: AMTraxTGE lost connection: Disconnected
traxmc-lobby-1     | [03:04:20 INFO]: - AMTraxTGE Disconnected
[07:04:22 INFO]: [connected player] AMTraxTGE (/1xx.xxx.xxx.xxx:xxxxx) has disconnected
[07:04:22 ERROR] [velocitab]: Failed to dispatch packet (is the client or server modded or using an illegal version?)
traxmc-proxy-1     | java.lang.NullPointerException: Cannot invoke "dev.simplix.protocolize.api.player.ProtocolizePlayer.sendPacket(Object)" because the return value of "dev.simplix.protocolize.api.providers.ProtocolizePlayerProvider.player(java.util.UUID)" is null
traxmc-proxy-1     |    at net.william278.velocitab.packet.ScoreboardManager.dispatchPacket(ScoreboardManager.java:57) ~[?:?]
traxmc-proxy-1     |    at net.william278.velocitab.packet.ScoreboardManager.lambda$updateRoles$4(ScoreboardManager.java:49) ~[?:?]
traxmc-proxy-1     |    at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
traxmc-proxy-1     |    at net.william278.velocitab.packet.ScoreboardManager.updateRoles(ScoreboardManager.java:49) ~[?:?]
traxmc-proxy-1     |    at net.william278.velocitab.tab.PlayerTabList.lambda$updatePlayer$17(PlayerTabList.java:156) ~[?:?]
traxmc-proxy-1     |    at java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:757) ~[?:?]
traxmc-proxy-1     |    at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735) ~[?:?]
traxmc-proxy-1     |    at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2182) ~[?:?]
traxmc-proxy-1     |    at net.william278.velocitab.tab.PlayerTabList.lambda$updatePlayer$18(PlayerTabList.java:152) ~[?:?]
traxmc-proxy-1     |    at java.util.concurrent.ConcurrentLinkedQueue.forEachFrom(ConcurrentLinkedQueue.java:1037) ~[?:?]
traxmc-proxy-1     |    at java.util.concurrent.ConcurrentLinkedQueue.forEach(ConcurrentLinkedQueue.java:1054) ~[?:?]
traxmc-proxy-1     |    at net.william278.velocitab.tab.PlayerTabList.updatePlayer(PlayerTabList.java:152) ~[?:?]
traxmc-proxy-1     |    at net.william278.velocitab.tab.PlayerTabList.lambda$updatePeriodically$21(PlayerTabList.java:183) ~[?:?]
traxmc-proxy-1     |    at java.util.concurrent.ConcurrentLinkedQueue.forEachFrom(ConcurrentLinkedQueue.java:1037) ~[?:?]
traxmc-proxy-1     |    at java.util.concurrent.ConcurrentLinkedQueue.forEach(ConcurrentLinkedQueue.java:1054) ~[?:?]
traxmc-proxy-1     |    at net.william278.velocitab.tab.PlayerTabList.lambda$updatePeriodically$22(PlayerTabList.java:182) ~[?:?]
traxmc-proxy-1     |    at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$1(VelocityScheduler.java:242) ~[velocity-3.2.0-SNAPSHOT-245.jar:3.2.0-SNAPSHOT (git-36cc2bde-b245)]
traxmc-proxy-1     |    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
traxmc-proxy-1     |    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
traxmc-proxy-1     |    at java.lang.Thread.run(Thread.java:833) [?:?]
[07:04:22 INFO]: [server connection] AMTraxTGE -> prison has disconnected
[07:04:22 ERROR] [velocitab]: Failed to dispatch packet (is the client or server modded or using an illegal version?)
traxmc-proxy-1     | java.lang.NullPointerException: Cannot invoke "dev.simplix.protocolize.api.player.ProtocolizePlayer.sendPacket(Object)" because the return value of "dev.simplix.protocolize.api.providers.ProtocolizePlayerProvider.player(java.util.UUID)" is null
traxmc-proxy-1     |    at net.william278.velocitab.packet.ScoreboardManager.dispatchPacket(ScoreboardManager.java:57) ~[?:?]
traxmc-proxy-1     |    at net.william278.velocitab.packet.ScoreboardManager.updateRoles(ScoreboardManager.java:50) ~[?:?]
traxmc-proxy-1     |    at net.william278.velocitab.tab.PlayerTabList.lambda$updatePlayer$17(PlayerTabList.java:156) ~[?:?]
traxmc-proxy-1     |    at java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:757) ~[?:?]
traxmc-proxy-1     |    at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735) ~[?:?]
traxmc-proxy-1     |    at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2182) ~[?:?]
traxmc-proxy-1     |    at net.william278.velocitab.tab.PlayerTabList.lambda$updatePlayer$18(PlayerTabList.java:152) ~[?:?]
traxmc-proxy-1     |    at java.util.concurrent.ConcurrentLinkedQueue.forEachFrom(ConcurrentLinkedQueue.java:1037) ~[?:?]
traxmc-proxy-1     |    at java.util.concurrent.ConcurrentLinkedQueue.forEach(ConcurrentLinkedQueue.java:1054) ~[?:?]
traxmc-proxy-1     |    at net.william278.velocitab.tab.PlayerTabList.updatePlayer(PlayerTabList.java:152) ~[?:?]
traxmc-proxy-1     |    at net.william278.velocitab.tab.PlayerTabList.lambda$updatePeriodically$21(PlayerTabList.java:183) ~[?:?]
traxmc-proxy-1     |    at java.util.concurrent.ConcurrentLinkedQueue.forEachFrom(ConcurrentLinkedQueue.java:1037) ~[?:?]
traxmc-proxy-1     |    at java.util.concurrent.ConcurrentLinkedQueue.forEach(ConcurrentLinkedQueue.java:1054) ~[?:?]
traxmc-proxy-1     |    at net.william278.velocitab.tab.PlayerTabList.lambda$updatePeriodically$22(PlayerTabList.java:182) ~[?:?]
traxmc-proxy-1     |    at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$1(VelocityScheduler.java:242) ~[velocity-3.2.0-SNAPSHOT-245.jar:3.2.0-SNAPSHOT (git-36cc2bde-b245)]
traxmc-proxy-1     |    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
traxmc-proxy-1     |    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
traxmc-proxy-1     |    at java.lang.Thread.run(Thread.java:833) [?:?]
traxmc-prison-1    | [03:04:22 INFO]: AMTraxTGE lost connection: Disconnected
traxmc-prison-1    | [03:04:22 INFO]: AMTraxTGE left the game
```
</details>

<details>
<summary>Config</summary>

```yml
# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃       Velocitab Config       ┃
# ┃    Developed by William278   ┃
# ┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
# ┗╸ Placeholders: %players_online%, %max_players_online%, %local_players_online%, %current_date%, %current_time%, %username%, %server%, %ping%, %prefix%, %suffix%, %role%
headers:
    default: "&aWelcome to &6TraxMC&a"
    prison: "&aWelcome to &dPrison&a on &6TraxMC&a!"
footers:
    default: "Players: %players_online%/%max_players_online%"
    prison: "Inmates: %local_players_online%"
formats:
    default: "&f%prefix%&f %username% &6%ping%&ams "
    prison: "&f%prefix%&f %username% &6%ping%&ams "
# Which text formatter to use (MINEDOWN or MINIMESSAGE)
formatting_type: MINEDOWN
# The servers in each group of servers
server_groups:
    default:
        - lobby
    prison:
        - prison
# All servers which are not in other groups will be put in the fallback group.
# "false" will exclude them from Velocitab.
fallback_enabled: true
# The formats to use for the fallback group.
fallback_group: default
enable_papi_hook: true
# If you are using MINIMESSAGE formatting, enable this to support MiniPlaceholders in formatting.
enable_miniplaceholders_hook: true
# Ordered list of elements by which players should be sorted. (ROLE_WEIGHT, ROLE_NAME and SERVER are supported)
sort_players_by:
    - ROLE_WEIGHT
    - ROLE_NAME
# How often to periodically update the TAB list, including header and footer, for all users.
# Will only update on player join/leave if set to 0.
update_rate: 10
```
</details>

I'm still configuring this server, so if there is a solution that happens to be a compatibility issue, I will update this

### PR DESCRIPTION
**Pull request by ironboundred**
Have not been able to reproduce using this.
Fixes #26 
image

### CODE REVIEW

File: src/main/java/net/william278/velocitab/tab/PlayerTabList.java [hunk 1]
```diff
@@ -154,6 +154,9 @@ public void replacePlayer(@NotNull TabPlayer tabPlayer) {
 
     // Update a player's name in the tab list
     public void updatePlayer(@NotNull TabPlayer tabPlayer) {
+        if (!tabPlayer.getPlayer().isActive()){
```
Comment (WiIIiam278) [inline src/main/java/net/william278/velocitab/tab/PlayerTabList.java:157]: style: could you just add a space between the last close parenthesis and the open curly parenthesis here?

**Review by WiIIiam278 — CHANGES_REQUESTED** [review]
Looks good - just one really minor style thing :)

**Review by WiIIiam278 — APPROVED** [review]
